- project:
    templates:
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
      - check-requirements
      - openstack-cover-jobs
      - openstack-python3-jobs-neutron
    check:
      jobs:
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
        - ovn-octavia-provider-functional-release
        - ovn-octavia-provider-functional-master
        - ovn-octavia-provider-tempest-release
        - ovn-octavia-provider-tempest-master:
            voting: false
        - kuryr-kubernetes-tempest-ovn-provider-ovn:
            voting: false
    gate:
      fail-fast: true
      jobs:
        - ovn-octavia-provider-functional-release
        - ovn-octavia-provider-functional-master
        - ovn-octavia-provider-tempest-release
